export const ROUTES = {
	welcomeScreen: "/",
	login: "/login",
	register: "/register",
	forgotPassword: "/forgot-password",
	createNewPassword: "/create-new-password",
	otp: "/otp",
	verifyAccount: "/verify-account",
	welcome: "/welcome",
	category: "/category/:category",
	subcategory: "/category/:category/:subcategory",
	mediaDetail: "/media/:mediaType/:mediaId",
	seasonDetail: "/media/tv/:seriesId/season/:seasonNumber",
	profile: "/profile",
	createProfile: "/profiles/create",
	logout: "/logout",
} as const;
